### ISSUE TITLE
Comments results in invalid XML fragments

### ISSUE THREAD

**Issue by marcelrassinger** [remuslazar/node-xmlsplit#2]
To reproduce run

node testXMLSplit.js --tag book order.xml 

Files are in the attached zip file.

Regards, Marcel

[bug.zip](https://github.com/remuslazar/node-xmlsplit/files/118890/bug.zip)

**Comment by marcelrassinger** [comment]
Sorry, I forgot: node version is 4.2.6

**Comment by remuslazar** [comment]
@marcelrassinger v1.2.5 (already pushed to the npm registry, see #3) should fix it. Could u please confirm that, so I can close this issue? Thanks!

**Comment by marcelrassinger** [comment]
It works! Thank you very much for the quick fix.

However, I run immediately in another bug: if you split the attached file by “book” then you get an invalid xml as second split. The reason is probably that I have a “book” element nested in another book. So a stack counter or something similar might get confused. I agree, the example is a little bit silly, but in the original huge products file the recursion makes sense.

Shall I open another bug?

Regards
Marcel

**Comment by remuslazar** [comment]
@marcelrassinger the current program logic assumes that the outer tag is kinda uniq and will not occur in the inner XML. Mainly for performance reasons the xml parsing being done quite "rude".. but I agree, this should be fixed.

Could u please fill another issue?
