### ISSUE TITLE
Nested elements having the same name result in invalid XML fragments

### ISSUE THREAD

**Issue by marcelrassinger** [remuslazar/node-xmlsplit#4]
To reproduce run

 node testXMLSplit.js -t book -i order2.xml -o out 

Files are in the attached zip file. "out" is the prefix of the output files. 
I think for most cases ist will be sufficient to split at the topmost "book". Maybe by using a stack counter.

[bug.zip](https://github.com/remuslazar/node-xmlsplit/files/132407/bug.zip)

**Comment by remuslazar** [comment]
@marcelrassinger could u pls check if the mentioned pr does fix your issue? Thanks!

**Comment by marcelrassinger** [comment]
Thanks, it works!
